# docker-compose.yml
version: '3.8'

services:
  # FastAPI Application
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_USER=apa_user
      - DB_PASSWORD=apa_password
      - DB_NAME=apa_evaluation
      - DB_PORT=3306
      - ENVIRONMENT=development
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./app:/app/app  # For development hot reload
    networks:
      - apa_network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=apa_evaluation
      - MYSQL_USER=apa_user
      - MYSQL_PASSWORD=apa_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - apa_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - apa_network
    restart: unless-stopped

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - apa_network
    restart: unless-stopped

networks:
  apa_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
